// Palavras-chave → categoria (usado pelo text-handler, sem IA)
export const CATEGORY_KEYWORDS: Record<string, string> = {
  mercado: 'Alimentação', supermercado: 'Alimentação', feira: 'Alimentação',
  hortifruti: 'Alimentação', padaria: 'Alimentação', açougue: 'Alimentação',
  restaurante: 'Alimentação', pizza: 'Alimentação', ifood: 'Alimentação',
  rappi: 'Alimentação', delivery: 'Alimentação', lanche: 'Alimentação',
  café: 'Alimentação', cafe: 'Alimentação', almoço: 'Alimentação',
  almoco: 'Alimentação', janta: 'Alimentação', jantar: 'Alimentação',
  uber: 'Transporte', '99': 'Transporte', taxi: 'Transporte', táxi: 'Transporte',
  ônibus: 'Transporte', onibus: 'Transporte', gasolina: 'Transporte',
  combustível: 'Transporte', combustivel: 'Transporte', estacionamento: 'Transporte',
  aluguel: 'Moradia', condomínio: 'Moradia', condominio: 'Moradia',
  iptu: 'Moradia', luz: 'Moradia', água: 'Moradia', agua: 'Moradia',
  gás: 'Moradia', gas: 'Moradia', internet: 'Moradia',
  farmácia: 'Saúde', farmacia: 'Saúde', médico: 'Saúde', medico: 'Saúde',
  consulta: 'Saúde', exame: 'Saúde', remédio: 'Saúde', remedio: 'Saúde',
  hospital: 'Saúde', cabelo: 'Saúde', salão: 'Saúde', salao: 'Saúde',
  manicure: 'Saúde', unha: 'Saúde', depilação: 'Saúde', depilacao: 'Saúde',
  sobrancelha: 'Saúde', academia: 'Saúde', pilates: 'Saúde', yoga: 'Saúde',
  dentista: 'Saúde', ortodontista: 'Saúde', psicólogo: 'Saúde',
  psicologo: 'Saúde', terapia: 'Saúde', dermatologista: 'Saúde',
  curso: 'Educação', livro: 'Educação', faculdade: 'Educação',
  escola: 'Educação', mensalidade: 'Educação', creche: 'Educação',
  material: 'Educação', apostila: 'Educação', mentoria: 'Educação',
  workshop: 'Educação',
  cinema: 'Lazer', netflix: 'Lazer', spotify: 'Lazer',
  bar: 'Lazer', viagem: 'Lazer', hotel: 'Lazer', hospedagem: 'Lazer',
  passagem: 'Lazer', aeroporto: 'Lazer', airbnb: 'Lazer',
  pousada: 'Lazer', teatro: 'Lazer', show: 'Lazer', ingresso: 'Lazer',
  parque: 'Lazer',
  roupa: 'Vestuário', sapato: 'Vestuário', tênis: 'Vestuário',
  tenis: 'Vestuário', loja: 'Vestuário',
  conta: 'Serviços', fatura: 'Serviços', parcela: 'Serviços', boleto: 'Serviços',
  celular: 'Serviços', telefone: 'Serviços', seguro: 'Serviços',
  contador: 'Serviços', contabilidade: 'Serviços', advogado: 'Serviços',
  faxina: 'Serviços', diarista: 'Serviços', empregada: 'Serviços',
  shopping: 'Compras', presente: 'Compras', amazon: 'Compras',
  shopee: 'Compras', shein: 'Compras', magalu: 'Compras',
  ração: 'Pets', racao: 'Pets', veterinário: 'Pets', veterinario: 'Pets',
  pet: 'Pets', petshop: 'Pets', cachorro: 'Pets', gato: 'Pets',
  cadelinha: 'Pets', cachorrinha: 'Pets', gatinha: 'Pets', gatinho: 'Pets',
  filhote: 'Pets', tosa: 'Pets', 'banho pet': 'Pets', antipulga: 'Pets',
  'vacina pet': 'Pets', vermifugo: 'Pets', vermífugo: 'Pets',
  dízimo: 'Outros', dizimo: 'Outros', oferta: 'Outros', igreja: 'Outros',
  mesada: 'Outros', doação: 'Outros', doacao: 'Outros',
  salário: 'Salário', salario: 'Salário', pagamento: 'Salário',
  freela: 'Freelance', freelance: 'Freelance', projeto: 'Freelance',
  dividendo: 'Investimentos', rendimento: 'Investimentos', juros: 'Investimentos',
  investimento: 'Investimentos', poupança: 'Investimentos', poupanca: 'Investimentos',
  retorno: 'Investimentos',
  venda: 'Vendas', vendi: 'Vendas', vendido: 'Vendas',
  comissão: 'Comissão', comissao: 'Comissão',
}

export const INCOME_CATEGORIES = ['Salário', 'Freelance', 'Investimentos', 'Vendas', 'Comissão']

export const STRONG_PET_KEYWORDS = [
  'cachorro',
  'cachorra',
  'gato',
  'gata',
  'cadelinha',
  'cachorrinha',
  'gatinha',
  'gatinho',
  'pet',
  'ração',
  'racao',
  'veterinária',
  'veterinaria',
  'veterinário',
  'veterinario',
  'vet',
  'clínica veterinária',
  'clinica veterinaria',
  'tosa',
  'filhote',
  'antipulga',
  'vermífugo',
  'vermifugo',
]

export const ERROR_MESSAGES = {
  PARSE_FAILED: 'Hmm, não entendi. Tenta assim: "gastei 45 no mercado" ou "recebi 3500 de salário"',
  OCR_FAILED: 'Isso não parece um recibo... Manda a foto de uma nota fiscal ou cupom!',
  AUDIO_FAILED: 'Não consegui entender o áudio. Tenta falar mais devagar ou digitar: "gastei 45 no mercado"',
  GENERIC_ERROR: 'Ops, algo deu errado. Tenta de novo em alguns segundos.',
}
